### ISSUE TITLE
Can't build new version

### ISSUE THREAD

**Issue by nrafal** [zbrox/rmq_monitor#11]
Hi!

Thanks for great tool :) It recently stopped working though, due to some problem with Slack certificate. I've tried to build new image for Docker from this repo, but it failed and I don't know cargo so I'm quite lost as to what is wrong. While building I have following error:
```
#0 49.12 error[E0432]: unresolved import `futures_core::core_reexport`
#0 49.12    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.3.4/src/lib.rs:542:9
#0 49.12     |
#0 49.12 542 | pub use futures_core::core_reexport;
#0 49.12     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `core_reexport` in the root
#0 49.13 
#0 49.13 error[E0433]: failed to resolve: could not find `document_join_macro` in `futures_util`
#0 49.13    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.3.4/src/lib.rs:561:15
#0 49.13     |
#0 49.13 561 | futures_util::document_join_macro! {
#0 49.13     |               ^^^^^^^^^^^^^^^^^^^ could not find `document_join_macro` in `futures_util`
#0 49.13 
#0 49.13 error[E0433]: failed to resolve: could not find `document_select_macro` in `futures_util`
#0 49.13    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.3.4/src/lib.rs:584:15
#0 49.13     |
#0 49.13 584 | futures_util::document_select_macro! {
#0 49.13     |               ^^^^^^^^^^^^^^^^^^^^^ could not find `document_select_macro` in `futures_util`
#0 49.13 
#0 49.13 error[E0603]: module `async_await` is private
#0 49.13    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.3.4/src/lib.rs:547:23
#0 49.13     |
#0 49.13 547 | pub use futures_util::async_await;
#0 49.13     |                       ^^^^^^^^^^^ private module
#0 49.13     |
#0 49.13 note: the module `async_await` is defined here
#0 49.13    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.21/src/lib.rs:34:1
#0 49.13     |
#0 49.13 34  | mod async_await;
#0 49.13     | ^^^^^^^^^^^^^^^
#0 49.13 
#0 49.14 Some errors have detailed explanations: E0432, E0433, E0603.
#0 49.14 For more information about an error, try `rustc --explain E0432`.
#0 49.15 error: could not compile `futures` (lib) due to 4 previous errors
#0 49.15 warning: build failed, waiting for other jobs to finish...
```

I suppose it's something with dependencies or new versions as the code is quite old. Are you able to look at that or is this project abandoned?

**Comment by zbrox** [comment]
Hey, I haven't tried it out in quite a while, glad it is useful to someone!

I quickly updated the crate to use the 2021 Rust edition and while I was added I updated all the dependencies. These days if I have time I will update the Docker image in the hub.

The new version 0.2.6 should be published soon: https://github.com/zbrox/rmq_monitor/actions/runs/4679000943

Since I did it quickly while I was on a break, I haven't tested it but it should be ok. If you see some problems while using this new version please report them.

Cheers!

**Comment by zbrox** [comment]
Well silly me, I had forgotten that the Docker image build is also automated. The updated Docker image is available on the Docker Hub.

**Comment by zbrox** [comment]
@nrafal drop a comment whenever you have had the opportunity to test this new version and you can confirm it's running fine
